name: Repository Dispatch Workflow
on:
  repository_dispatch:
    types: execute_go
  workflow_dispatch:

jobs:
  env:
    HELLO: Hello
  execute_go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Execute Go from repository_dispatch
        if: ${{ github.event_name == 'repository_dispatch' && github.event.action == 'execute_go' }}
        env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: |
          echo ${{ github.event.client_payload.message }} >> $HELLO
          go run .

      - name: Execute Go from workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo $HELLO
          echo execute_go from workflow_dispatch
