name: Repository Dispatch Workflow
on:
  repository_dispatch:
    types: execute_go
  workflow_dispatch:

jobs:
  execute_go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Execute Go
        if: github.event_name != 'repository_dispatch'
        run: echo execute_go from workflow_dispatch

        if: github.event_name == 'repository_dispatch'
        env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: go run .
