name: Repository Dispatch Workflow
on:
  repository_dispatch:
    types: execute_go
  workflow_dispatch:
    inputs:
      message:
        required: true
        type: string
      stage:
        required: true
        type: choice
        options:
          - dev
          - qa1
          - prd
      pathver:
        required: false
        type: string
        default: "v1"

jobs:
  execute_go:
    env:
      HELLO: ${{ inputs.message }}
      STAGE: ${{ inputs.stage }}
      PATHVER: ${{ inputs.pathver }}
    runs-on: ubuntu-latest
    steps:
      - name: Override Env Values
        if: ${{ github.event_name == 'repository_dispatch' && github.event.action == 'execute_go' }}
        run: |
          echo "HELLO=${{ github.event.client_payload.message }}" >> $GITHUB_ENV
          echo "STAGE=dev" >> $GITHUB_ENV
          echo "PATHVER=v1" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: apidoc/${{ env.STAGE }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Execute Go from repository_dispatch
        if: ${{ github.event_name == 'repository_dispatch' && github.event.action == 'execute_go' }}
        env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: |
          echo ${{ env.HELLO }}
          echo ${{ env.PATHVER }}
          go run .

      - name: Execute Go from workflow_dispatch
        #if: github.event_name == 'workflow_dispatch'
        run: |
          echo ${{ env.HELLO }}
          echo ${{ env.PATHVER }}
          echo execute_go from workflow_dispatch
          git push origin apidoc/${{ env.STAGE }}
