name: Repository Dispatch Workflow
on:
  repository_dispatch:
    types: execute_go
  workflow_dispatch:
env:
  env_1: hashito
jobs:
  execute_go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Execute Go from repository_dispatch
        if: ${{ github.event_name == 'repository_dispatch' && github.event.action == 'execute_go' }}
        env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: |
          env_1=${{ github.event.client_payload.message }}
          go run .

      - name: Execute Go from workflow_dispatch
        run: |
          echo $env_1
          echo execute_go from workflow_dispatch
