name: run-workflow-actions
on:
  workflow_dispatch:

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Generate github token
      #   id: generate_token
      #   uses: tibdex/github-app-token@v2
      #   with:
      #     app_id: ${{ secrets.APP_ID }}
      #     private_key: ${{ secrets.PRIVATE_KEY }}

      # - name: Execute test.yml
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: gh workflow run test.yml

      - name: Execute repository_dispatch_by_gh
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: n-aoki0409/test_gitaction
          event-type: execute_go
          client-payload: '{"message": "Hello from github actions by gh!!"}'

      # - name: Execute repository_dispatch_by_curl
      #   env:
      #     TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      #   run: |
      #     curl -i \
      #       -X POST \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "Authorization: Bearer $TOKEN" \
      #       -H "X-GitHub-Api-Version: 2022-11-28" \
      #       https://api.github.com/repos/n-aoki0409/test_gitaction/dispatches \
      #       -d '{"event_type":"execute_go","client_payload":{"message":"Hello from github actions by curl!!"}}'

      # - name: Execute repository_dispatch_by_github_app
      #   env:
      #     TOKEN: ${{ steps.generate_token.outputs.token }}
      #   run: |
      #     curl -L \
      #       -X POST \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "Authorization: Bearer $TOKEN" \
      #       -H "X-GitHub-Api-Version: 2022-11-28" \
      #       https://api.github.com/repos/n-aoki0409/test_gitaction/dispatches \
      #       -d '{"event_type":"execute_go","client_payload":{"message":"Hello from run_workflow.yml by github app!!"}}'
